{
 "title": "Summary",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Bed Time For Performance Level",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH latency AS (\n  WITH Q AS (\n\t  SELECT percentile_disc(0.5) within group (order by sleep_data.onset_latency) as latency\n\t  FROM sleep_data\n\t  WHERE sleep_data.summary_date >= now() - interval '30d'\n  )\n  SELECT latency, (now() AT TIME ZONE 'CST')::DATE as date FROM Q\n),\nday_of_week as (select extract(isodow from DATE 'tomorrow' AT TIME ZONE 'CST') as d),\nday as (\nselect CASE \n WHEN day_of_week.d =1 THEN 'MONDAY'\n WHEN day_of_week.d =2 THEN 'TUESDAY'\n WHEN day_of_week.d=3 THEN 'WEDNESDAY'\n WHEN day_of_week.d=4 THEN 'THURSDAY'\n WHEN day_of_week.d=5 THEN 'FRIDAY'\n WHEN day_of_week.d=6 THEN 'SATURDAY'\n WHEN day_of_week.d=7 THEN 'SUNDAY'\n ELSE 'OTHER'\n END from day_of_week \n)\nSELECT\n\t(\n\t\t(date_trunc('day', now() AT TIME ZONE 'CST' + INTERVAL '1 day') AT TIME ZONE 'CST') \n\t\t+ INTERVAL '4h'\n\t\t+ INTERVAL '1h' * sleep_schedule.hour \n\t\t+ INTERVAL '1m' * sleep_schedule.minute\n\t\t- sleep_coach.total_sleep_predicted * INTERVAL '1s'\n\t\t- latency.latency * INTERVAL '1s'\n\t) AT TIME ZONE 'CST' as time,\n\tsleep_coach.readiness_level as performance_level,\n \tsleep_coach.total_sleep_predicted,\n \tlatency.latency,\n \tformat('%s:%s', sleep_schedule.hour, sleep_schedule.minute) as wake_up_time\nFROM sleep_schedule\nJOIN day ON day.case = sleep_schedule.day\nJOIN sleep_coach ON sleep_coach.prediction_date::DATE = (now() AT TIME ZONE 'CST')::DATE\nJOIN latency ON latency.date = (now() AT TIME ZONE 'CST')::DATE"
    },
    { "rawSql": "\n" }
   ]
  },
  {
   "title": "Total Sleep Recommended Today (Hours)",
   "type": "bargauge",
   "description": "\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \nprediction_date as time,\ntotal_sleep_predicted as PEAK\nFROM sleep_coach\nWHERE readiness_level='PEAK' AND prediction_date::DATE = (now() AT TIME ZONE 'CST')::DATE\n"
    },
    {
     "rawSql": "SELECT \nprediction_date as time,\ntotal_sleep_predicted as GET_BY\nFROM sleep_coach\nWHERE readiness_level='GET_BY' AND prediction_date::DATE = (now() AT TIME ZONE 'CST')::DATE\n\n"
    },
    {
     "rawSql": "SELECT \nprediction_date as time,\ntotal_sleep_predicted as EASY\nFROM sleep_coach\nWHERE readiness_level='EASY' AND prediction_date::DATE = (now() AT TIME ZONE 'CST')::DATE"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  score\nFROM\n  readiness_data\nORDER BY summary_date DESC\nLIMIT 1"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  score\nFROM\n  sleep_data\nORDER BY summary_date DESC\nLIMIT 1"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  score\nFROM\n  activity_data\nORDER BY summary_date DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Daily Readiness Score",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  (summary_date::TIMESTAMP AT TIME ZONE 'CST') as time,\n  score\nFROM\n  readiness_data\nWHERE\n  $__timeFilter(summary_date::TIMESTAMP)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Daily Sleep Score",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  (summary_date::TIMESTAMP AT TIME ZONE 'CST') as time,\n  score\nFROM\n  sleep_data\nWHERE\n  $__timeFilter(summary_date::TIMESTAMP)\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Daily Activity Score",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  (summary_date::TIMESTAMP AT TIME ZONE 'CST') as time,\n  score\nFROM\n  activity_data\nWHERE\n  $__timeFilter(summary_date::TIMESTAMP)\nORDER BY time\n"
    }
   ]
  },
  {
   "type": "gauge",
   "description": "Latency in the past 30 days is the measurement for sleep coach contribution",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "WITH Q AS (\n\tSELECT \n\t    percentile_disc(0.5) within group (order by sleep_data.onset_latency) as median_latency\n  \tFROM sleep_data\n  \tWHERE sleep_data.summary_date >= now() - interval '30d'\n)\nSELECT median_latency, now() AT TIME ZONE 'CST' as time FROM Q\n"
    }
   ]
  },
  {
   "title": "Sleep Latency",
   "type": "graph",
   "description": " Detected latency from bedtime_start to the beginning of the first five minutes of persistent sleep. ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "dthms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  (summary_date::TIMESTAMP AT TIME ZONE 'CST') as time,\n  onset_latency\nFROM\n  sleep_data\nWHERE\n  $__timeFilter(summary_date::TIMESTAMP )\nORDER BY time\n"
    },
    {
     "rawSql": "WITH Q AS (\n  SELECT \n    (summary_date::TIMESTAMP AT TIME ZONE 'CST') as time,\n    AVG(onset_latency) OVER(ORDER BY (summary_date::TIMESTAMP AT TIME ZONE 'CST') ROWS BETWEEN 7 PRECEDING AND CURRENT ROW) AS value,\n    'Weekly Moving Average' as metric \n  FROM sleep_data\n  ORDER BY time ASC\n)\nSELECT time, value, metric FROM Q\nWHERE $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Log Event Into DB",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 31 },
   "content": "<form id=\"event-form\">\n  <label for=\"event\">Event Name:</label><br>\n  <input type=\"text\" id=\"event\" name=\"event\"><br>\n  <br/>\n  <label for=\"lname\">Date of Event:</label><br>\n  <input type=\"date\" id=\"date\" name=\"date\">\n  <input type=\"submit\" value=\"Submit\">\n</form>\n<script>\n  document.getElementById('event-form').addEventListener('submit', function (e) {\n    e.preventDefault()\n    \n    const event = document.getElementById('event').value\n    const date = document.getElementById('date').value\n    const sql = `SELECT now() as time FROM events LIMIT 1; INSERT INTO events (name, event_datetime\\) VALUES ('${event}', '${date}'\\)`\n    \n    fetch('/api/tsdb/query', {\n      method: 'POST',\n      headers: {\n        'Content-type': 'application/json',\n      },\n\n      body: JSON.stringify({\n        queries: [\n          {\n            datasourceId: 1,\n            rawSql: sql,\n          }\n        ]\n      })\n    }).then(data => {\n      console.log(data)\n    }).catch(e => {\n      console.log(e)\n    })\n  })\n</script>",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Event Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\n  event_datetime AT TIME ZONE 'CST' AS \"time\",\n  name AS metric\nFROM events\nWHERE\n  $__timeFilter(event_datetime)\nORDER BY event_datetime"
    }
   ]
  },
  {
   "title": "Model Performance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  (prediction_date::TIMESTAMP AT TIME ZONE 'CST') AS time,\n  total_sleep_obtained,\n  total_sleep_predicted\nFROM\n  sleep_coach\nWHERE\n  $__timeFilter(prediction_date::TIMESTAMP)\nORDER BY id\n"
    }
   ]
  }
 ]
}